(function(g){var window=this;'use strict';var Bob=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");-1===c&&(c=a.length);var d="-"===a[0]?"-":"";d&&(a=a.substring(1));return d+(0,g.jdb)("0",Math.max(0,b-c))+a},Cob=function(){return{I:"svg",
Y:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},X:[{I:"path",Y:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},Dob=function(){return{I:"svg",
Y:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},X:[{I:"path",Y:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},Fob=function(a){"number"===typeof a?(this.date=Eob(a,0,1),z6(this,1)):g.Xa(a)?(this.date=Eob(a.getFullYear(),a.getMonth(),a.getDate()),z6(this,a.getDate())):(this.date=new Date(g.eb()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),z6(this,a))},Eob=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},z6=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},A6=function(a,b){g.yU.call(this,a,{I:"div",
T:"ytp-reminder-menu",Y:{role:"menu",tabindex:"-1"},X:[{I:"div",T:"ytp-reminder-menu-contents",X:[{I:"div",T:"ytp-reminder-menu-items"}]}]},100,!0);this.buttonElement=b;this.j=[];this.menuPopupRenderer=void 0;this.items=this.Ha("ytp-reminder-menu-items");this.hide()},Hob=function(a){var b=Gob(a),c=0,d={};
for(c=0;c<b.length;d={eO:d.eO},c++){var e=a.j[c];e||(e=new g.T({I:"div",T:"ytp-reminder-menu-item",Y:{role:"menuitem",tabindex:"0"},X:[{I:"div",T:"ytp-reminder-menu-item-icon",Aa:"{{icon}}"},{I:"div",T:"ytp-reminder-menu-item-label",Aa:"{{text}}"}]}),d.eO=c,e.Ua("click",function(l){return function(){var m=l.eO;a.Rb();m=Gob(a)[m];a.ra("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.Ga(a.items),a.j[c]=e);
var f=b[c],h=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":h=Cob();break;case "NOTIFICATIONS_NONE":h=Dob();break;case "NOTIFICATIONS_ACTIVE":h=g.Nua()}f=f.text?g.yG(f.text):"";e.update({icon:h,text:f})}for(;c<a.j.length;)a.j.pop().dispose();0===c?a.Rb():a.zd(a.buttonElement)},Gob=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},B6=function(a){g.T.call(this,{I:"div",
X:[{I:"button",Oa:["ytp-offline-slate-button","ytp-button"],X:[{I:"div",T:"ytp-offline-slate-button-icon",Aa:"{{icon}}"},{I:"div",T:"ytp-offline-slate-button-text",Aa:"{{text}}"}]}]});this.J=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.B=void 0;this.D=this.j=null;(this.buttonElement=this.Ha("ytp-offline-slate-button"))&&this.V(this.buttonElement,"click",this.G);this.hide()},Job=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=
b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&g.S(c,Iob)?a.upcomingEventReminderButtonRenderer=g.S(c,Iob):c&&g.S(c,Iob)||(a.upcomingEventReminderButtonRenderer=null);C6(a)},C6=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.yG(b.toggledText):"";a.update({text:c,icon:Kob(b.toggledIcon)})}else c=b.defaultText?g.yG(b.defaultText):"",a.update({text:c,icon:Kob(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=Lob(a))?(c=b.text?g.yG(b.text):"",a.update({text:c,icon:Kob(b.icon)}),a.show()):a.hide():a.hide()},Nob=function(a,b,c){a.D||(a.D=new g.PE(a.J.W().Cl));
var d={context:g.uqa(a.D.config_||g.oE())};g.SF()&&(d.context.clientScreenNonce=g.SF());d.params=c;g.QE(a.D,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.B&&(a.upcomingEventReminderButtonRenderer.currentState=a.B,a.B=void 0)},
onError:function(){Mob(a)},
onTimeout:function(){Mob(a)}})},Mob=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,C6(a)):a.upcomingEventReminderButtonRenderer&&(a.B=void 0,C6(a))},Kob=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return Cob();case "NOTIFICATIONS_NONE":return Dob();case "NOTIFICATIONS_ACTIVE":return g.Nua();default:return null}},Lob=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.B||a.upcomingEventReminderButtonRenderer.currentState;a=g.u(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=g.S(c.value,Oob))&&c.state===b&&c.button&&g.S(c.button,g.mN))return g.S(c.button,g.mN);return null},Pob=function(a){g.T.call(this,{I:"div",
T:"ytp-offline-slate",X:[{I:"div",T:"ytp-offline-slate-background"},{I:"div",T:"ytp-offline-slate-bar",X:[{I:"span",T:"ytp-offline-slate-icon",X:[{I:"svg",Y:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},X:[{I:"path",Y:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{I:"circle",Y:{cx:"12",cy:"12",r:"3"}}]}]},{I:"span",T:"ytp-offline-slate-messages",X:[{I:"div",T:"ytp-offline-slate-main-text",Y:{"aria-label":"{{label}}"},Aa:"{{mainText}}"},{I:"div",T:"ytp-offline-slate-subtitle-text",Aa:"{{subtitleText}}"}]},{I:"span",T:"ytp-offline-slate-buttons"}]},{I:"button",Oa:["ytp-offline-slate-close-button","ytp-button"],X:[g.BG()]},{I:"button",Oa:["ytp-offline-slate-open-button","ytp-button"],X:[g.AG()]}]});var b=this;this.api=a;this.j=this.B=null;this.background=this.Ha("ytp-offline-slate-background");
this.C=this.Ha("ytp-offline-slate-bar");this.G=new g.fu(function(){g.nu(b.C,"ytp-offline-slate-bar-fade")},15E3);
this.K=!1;this.D=new g.fu(function(){g.nu(b.element,"ytp-offline-slate-collapsed")},15E3);
g.L(this,this.D);g.L(this,this.G);this.countdownTimer=new g.fu(this.D_,1E3,this);this.V(a,"presentingplayerstatechange",this.H_);this.V(a,"livestatedata",this.Sa);a=this.Ha("ytp-offline-slate-close-button");this.V(a,"click",function(){g.nu(b.element,"ytp-offline-slate-collapsed")});
a=this.Ha("ytp-offline-slate-open-button");this.V(a,"click",function(){g.pu(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.Sa(a);a=8===this.api.getPresentingPlayerType()&&!this.getVideoData().Tl;var c=8===this.api.getPresentingPlayerType();g.ru(this.element,"ytp-offline-slate-premiere-trailer",a);g.ru(this.element,"ytp-offline-slate-hide-background",c)},Qob=function(a,b,c){if(b){var d=null!=b.subtitleText?g.yG(b.subtitleText):"";
c=c?c:null!=b.mainText?g.yG(b.mainText):"";var e,f,h,l;b=null!=(l=null==(e=b.mainText)?void 0:null==(f=e.accessibility)?void 0:null==(h=f.accessibilityData)?void 0:h.label)?l:c;a.update({mainText:c,subtitleText:d,label:b});g.ru(a.element,"ytp-offline-slate-single-text-line",!d);g.ru(a.C,"ytp-offline-slate-bar-hidden",!c&&!d)}},D6=function(a,b){var c=(0,g.OD)();
this.module="heartbeat";this.trigger=a;this.j=b;this.C=c},Yob=function(a){g.zV.call(this,a);
var b=this;this.S=!1;this.ma=0;this.G=!1;this.B=new g.fu(function(){var e=b.player.W(),f=b.getVideoData();E6(b)&&(Rob(b)?Sob(b,e,f):(Tob(b),Uob(b,e,f)))},0);
this.j=this.heartbeatParams=null;this.D=!1;this.K=new g.ul(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.qa=new g.PE(void 0);this.ea=this.attestationResponse=void 0;this.utcOffsetMinutes=-(new Fob).getTimezoneOffset();this.C=new g.aL(this);g.L(this,this.B);g.L(this,this.C);Tob(this);Vob(this);this.C.V(a,"heartbeatparams",this.uE);this.C.V(a,"presentingplayerstatechange",this.f1);this.C.V(a,"videoplayerreset",this.j1);this.C.V(a,g.rK("heartbeat"),this.onCueRangeEnter);this.D&&this.j&&
Wob(this,void 0,this.j);var c=new g.qK(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.qK(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.wf([c,d]);Xob(this)},Xob=function(a){var b=a.getVideoData();
b.Kl&&(b=b.botguardData)&&g.SKa(b,a.player.W())},Tob=function(a){var b=a.getVideoData();
if(b.Kl&&(b=new g.OKa(b),g.AI.isInitialized()||3<=a.sequenceNumber)){var c=null;if(b.videoData.Hk){var d=g.PKa(b);if(d){c={};var e={};d=d.split("&");d=g.u(d);for(var f=d.next();!f.done;f=d.next())f=f.value.split("="),2===f.length&&(e[f[0]]=f[1]);e.r1a&&(c.webResponse=e.r1a);e.r1c&&(c.error=Zob[Number(e.r1c)]);c.challenge=b.videoData.Hk}}a.attestationResponse=c||void 0}},Rob=function(a){var b=a.getVideoData();
if(!g.BT(a.getVideoData())||b.KZ)return!1;if(b.useInnertubeDrmService()&&b.K){a="playready"===b.K.flavor&&b.N("html5_innertube_heartbeats_for_playready");var c="widevine"===b.K.flavor&&b.N("html5_innertube_heartbeats_for_widevine");b=g.DR(b.K)&&b.N("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},$ob=function(a){if(Rob(a))return!!a.heartbeatParams;
var b=a.getVideoData();return g.BT(a.getVideoData())&&b.useInnertubeDrmService()&&!b.Hl&&!b.hC?!1:!!b.heartbeatToken},F6=function(a,b){if(!a.B.isActive()&&a.S){var c=a.getVideoData();
if($ob(a)||c.isLivePlayback){if(void 0===b)if(a.G)if(a.D)b=7500;else{var d;b=(null==(d=a.heartbeatParams)?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().KX||6E4}else b=1E3;a.B.start(b)}}},dpb=function(a,b,c){b.Fo&&(c=g.Gl(c,{internalipoverride:b.Fo}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.xb&&(d.kpt=b.xb);c=g.Gl(c,d);g.oC(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.B.isActive()&&E6(a)){a.K.reset();a.sequenceNumber++;e=e.responseText;var f=apb(e);if(f){a.player.Ta("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(bpb))?"0"===h[1]?0:1:-1;cpb(a,void 0,f,e,h)}},
onError:function(e){E6(a)&&G6(a,!0,"net-"+e.status)},
onTimeout:function(){E6(a)&&G6(a,!0,"timeout")},
withCredentials:!0})},Sob=function(a,b,c){var d;
if(null!=(d=a.heartbeatParams)&&d.url){var e=g.Gl(a.heartbeatParams.url,{request_id:g.Nra()});c.va&&(e=g.Gl(e,{vvt:c.va}),c.mdxEnvironment&&(e=g.Gl(e,{mdx_environment:c.mdxEnvironment})));g.DS(b,c.oauthToken).then(function(f){f&&(e=g.Gl(e,{access_token:f}));dpb(a,c,e)})}},E6=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.cH(a.player.Vb(a.getPlayerType()),4)?!1:$ob(a)||b.isLivePlayback?!0:(H6(a),!1)},Uob=function(a,b,c){var d,e={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:null!=(d=a.va)?d:c.heartbeatServerData};a.ea=a.attestationResponse;c.Kl&&(e.attestationResponse=a.ea);var f=g.WT(c),h;d=null!=(h=f.client)?h:{};d.utcOffsetMinutes=a.utcOffsetMinutes;e.context=f;e.cpn=c.clientPlaybackNonce;if(h="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)d.timeZone=h;h={heartbeatChecks:[]};if(d=c.getPlayerResponse())c.heartbeatToken&&(e.heartbeatToken=c.heartbeatToken),(d=d.playabilityStatus)&&
(d=d.liveStreamability)&&d.liveStreamabilityRenderer&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.UJ(b)){h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");f=epb(a);d={};null!==f&&(d.clientPlayerPositionUtcMillis=f);var l,m;f=(null==(m=null==(l=a.player.Gb())?void 0:g.OV(l))?void 0:m.freePreviewWatchedDuration)||0;0<f&&(d.freePreviewWatchedDuration={seconds:""+f});h.unpluggedParams=d}e.heartbeatRequestParams=
h;c.isLivePlayback?(l=epb(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={utcTimeMillis:l})):b.N("enable_heartbeat_vod_playback_position")&&(l=fpb(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={streamTimeMillis:l}));a.player.ra("heartbeatRequest",e);var n={timeout:3E4,onSuccess:function(p){if(!a.B.isActive()&&E6(a)){var q=a.getVideoData(),r=q.Kl&&null==a.ea,t;q.Kl=!(null==(t=p.heartbeatAttestationConfig)||!t.requiresAttestation)||
r;r=p.playabilityStatus;t=JSON.stringify(r)||"{}";p.authenticationMismatch&&a.player.ya("authshear",{});var v=-1;var x=p.playabilityStatus;x&&(a.player.Ta("onHeartbeat",x),"OK"===x.status?v=p.stopHeartbeat?2:0:"UNPLAYABLE"===x.status?v=1:"LIVE_STREAM_OFFLINE"===x.status&&(v=0));a.sequenceNumber&&-1===v||a.K.reset();a.sequenceNumber++;p.heartbeatServerData&&(a.va=p.heartbeatServerData);q.jC=p;(x=p.playerCueRangeSet)&&g.zQa(q,x);p.playerCueRanges&&0<p.playerCueRanges.length&&(q.cueRanges=p.playerCueRanges);
var C,G;(null==(C=p.progressBarConfig)?0:C.progressBarStartPosition)&&(null==(G=p.progressBarConfig)?0:G.progressBarEndPosition)&&(q.progressBarStartPosition=p.progressBarConfig.progressBarStartPosition,q.progressBarEndPosition=p.progressBarConfig.progressBarEndPosition);q.compositeLiveIngestionOffsetToken=p.compositeLiveIngestionOffsetToken;p.compositeLiveStatusToken!==q.compositeLiveStatusToken&&(q.compositeLiveStatusToken=p.compositeLiveStatusToken);q.ra("dataupdated");cpb(a,p,r,t,v)}},
onError:function(p){E6(a)&&G6(a,!0,"net-"+p.status)},
onTimeout:function(){E6(a)&&G6(a,!0,"timeout")}};
g.DS(b,g.RT(c)).then(function(p){p&&(n.DU="Bearer "+p);g.QE(a.qa,"player/heartbeat",e,n)})},cpb=function(a,b,c,d,e){-1===e?(c="decode "+g.rg(d,3),G6(a,!1,c)):2===e?(H6(a),a.G=!0):(a.ma=0,a.B.stop(),1===e?(a.G=!1,c&&"PLAYABILITY_ERROR_CODE_EMBARGOED"===c.errorCode&&a.player.Xn(!0),a.player.Sg("heartbeat.stop",2,a.xf(d)),g.zD("heartbeatActionPlayerHalted",gpb(c)),(null==b?0:b.videoTransitionEndpoint)&&c&&(b=b.videoTransitionEndpoint,(d=g.S(b,g.sT))&&hpb(a,d,c,{itct:null==b?void 0:b.clickTrackingParams}))):
(a.G=!0,d=0,a.D&&c&&(d=Wob(a,b,c),a.player.ra("livestatedata",c)),d?F6(a,d):F6(a)))},Wob=function(a,b,c){var d=c.liveStreamability&&c.liveStreamability.liveStreamabilityRenderer,e=!(!d||!(d.switchStreamsImmediately||d.transitionTiming&&"STREAM_TRANSITION_TIMING_IMMEDIATELY"===d.transitionTiming));
b=ipb(a,b,d);var f=a.getVideoData(),h=a.player.Vb(a.getPlayerType()),l=h.isPlaying()&&!g.GT(f)&&!a.player.isAtLiveHead(a.getPlayerType());if(f.W().Yc()){var m,n=(null==(m=a.player.yf())?void 0:m.xc())||{};n.status=c.status||"";n.dvr=""+ +l;n["switch"]=""+ +e;n.ended=""+ +!(!d||!d.displayEndscreen);a.player.ya("heartbeat",n)}if(l&&!e)return b;e=d&&d.streamTransitionEndpoint&&g.S(d.streamTransitionEndpoint,g.sT);if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(d&&d.transitionTiming))a.getVideoData().transitionEndpointAtEndOfStream=
e;else if(e&&hpb(a,e,c))return b;if("OK"===c.status.toUpperCase()){e=d&&d.broadcastId;m=a.j&&a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer&&a.j.liveStreamability.liveStreamabilityRenderer.broadcastId;l=e!==m&&null!=e;if(!jpb(a,f)||l){var p={video_id:f.videoId};f.LL&&(p.is_live_destination="1");a.player.N("web_player_heartbeat_request_watch_next")||(p.disable_watch_next=!0,p.raw_watch_next_response=f.Jd);p.autonav_state=f.autonavState;p.oauth_token=f.oauthToken;p.force_gvi=
f.Eo;p.xm=f.xm;f.G&&(p.vss_credentials_token=f.G,p.vss_credentials_token_type=f.Hm);f.va&&(p.vvt=f.va);d=void 0;jpb(a,f)?l&&(d=new D6("broadcastIdChanged",m+","+e),a.xI("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",c)):(e&&(d=new D6("formatsReceived",""+e)),a.xI("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",c));a.player.loadVideoByPlayerVars(p,void 0,void 0,void 0,d);return b}a.player.Fg("heartbeat",
a.getPlayerType())}d&&d.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.K=!0,a.Ib&&a.api.eB()):g.ZL(h)&&(f=(null==(p=a.player.yf())?void 0:p.xc())||{},a.player.ya("hbse",f,!0),a.player.eB(),a.player.Ta("onLiveMediaEnded",c)));return b},jpb=function(a,b){return a.player.N("web_player_heartbeat_has_media_urls")?g.ET(b):!(!b.hlsvp&&!b.Qb)},ipb=function(a,b,c){return a.player.N("web_player_use_heartbeat_poll_delay_ms")&&(a=Number(null==b?void 0:b.pollDelayMs))?a:(c=Number(null==c?void 0:c.pollDelayMs))?
c:0},G6=function(a,b,c){var d=a.player.W();
if(!a.B.isActive()){a.B.stop();a.ma++;var e=b?"heartbeat.net":"heartbeat.servererror";var f=a.getVideoData();if(f.fZ||b&&!g.BT(a.getVideoData())&&!$ob(a)&&f.isLivePlayback)f=!1;else{var h,l;(null==(l=a.heartbeatParams)?0:l.VA)?h=a.heartbeatParams.VA:h=f.TX||5;f=a.ma>=h}f?(g.zD("heartbeatActionPlayerHalted",b?{enforcedPolicyToHaltOnNetworkFailure:!0}:gpb()),(b=a.getVideoData())&&b.isLivePlayback?a.player.Sg(e,1,"Video playback interrupted. Please try again.",c):a.player.Sg(e,1,"Sorry, there was an error licensing this video.",
c)):(d.N("html5_report_non_fatal_heartbeat_error")&&a.player.Ir(e,{msg:c}),F6(a,a.K.getValue()),g.vl(a.K))}},gpb=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},H6=function(a){a.ma=0;
a.B.stop();a.G=!1;a.sequenceNumber=0},Vob=function(a){var b=a.getVideoData(),c=a.player.W();
if(b.isLivePlayback)if(g.pOa(c.G)){a.D=!0;a.S=!0;if(!g.WJ(c)||g.UJ(c))a.offlineSlate=new Pob(a.player),g.L(a,a.offlineSlate),g.sU(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.j=b.playabilityStatus);var d;"UNPLAYABLE"!==(null==(d=a.j)?void 0:d.status)&&(a.j?(d=ipb(a,void 0,a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer))?F6(a,d):F6(a,7500):F6(a,1E3))}else a.player.Sg("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.Db(b.Fa,"heartbeat")&&a.player.Fg("heartbeat",a.getPlayerType())},hpb=function(a,b,c,d){var e=b&&b.videoId;
return e?(a.player.Ao(e,Object.assign({},{autonav:"1"},d||{}),void 0,!0,!0,b,g.RT(a.getVideoData())),a.xI("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",c),!0):!1},epb=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(1E3*a):null},fpb=function(a){return(a=a.player.getCurrentTime(a.getPlayerType()))&&isFinite(a)?""+Math.floor(1E3*a):null},apb=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},kpb={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},lpb=kpb;lpb=kpb;var Zob=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"];g.k=Fob.prototype;g.k.GV=lpb.FIRSTDAYOFWEEK;g.k.HV=lpb.FIRSTWEEKCUTOFFDAY;
g.k.clone=function(){var a=new Fob(this.date);a.GV=this.GV;a.HV=this.HV;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getYear=function(){return this.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.getTime=function(){return this.date.getTime()};
g.k.getDay=function(){return this.date.getDay()};
g.k.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.k.getUTCMonth=function(){return this.date.getUTCMonth()};
g.k.getUTCDate=function(){return this.date.getUTCDate()};
g.k.getUTCDay=function(){return this.date.getDay()};
g.k.getUTCHours=function(){return this.date.getUTCHours()};
g.k.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.k.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.setFullYear=function(a){this.date.setFullYear(a)};
g.k.setYear=function(a){this.setFullYear(a)};
g.k.setMonth=function(a){this.date.setMonth(a)};
g.k.setDate=function(a){this.date.setDate(a)};
g.k.setTime=function(a){this.date.setTime(a)};
g.k.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};
g.k.setUTCMonth=function(a){this.date.setUTCMonth(a)};
g.k.setUTCDate=function(a){this.date.setUTCDate(a)};
g.k.add=function(a){if(a.years||a.months){var b=this.getMonth()+a.months+12*a.years,c=this.getYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.days&&(c=this.getYear(),b=0<=c&&99>=c?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.setDate(1),this.setFullYear(a.getFullYear()+
b),this.setMonth(a.getMonth()),this.setDate(a.getDate()),z6(this,a.getDate()))};
g.k.equals=function(a){return!(!a||this.getYear()!=a.getYear()||this.getMonth()!=a.getMonth()||this.getDate()!=a.getDate())};
g.k.toString=function(){var a=this.getFullYear(),b=0>a?"-":1E4<=a?"+":"";return[b+Bob(Math.abs(a),b?6:4),Bob(this.getMonth()+1,2),Bob(this.getDate(),2)].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};var mpb=new g.Pv("addUpcomingEventReminderEndpoint");var npb=new g.Pv("removeUpcomingEventReminderEndpoint");var opb=new g.Pv("updateUpcomingEventReminderButtonStateCommand");var Iob=new g.Pv("upcomingEventReminderButtonRenderer"),Oob=new g.Pv("upcomingEventReminderButtonStateRenderer");g.w(A6,g.yU);A6.prototype.hide=function(){this.buttonElement&&this.buttonElement.removeAttribute("aria-haspopup");g.yU.prototype.hide.call(this)};
A6.prototype.show=function(){this.buttonElement&&this.buttonElement.setAttribute("aria-haspopup","true");g.yU.prototype.show.call(this)};
A6.prototype.Ba=function(){g.tb(this.j);g.yU.prototype.Ba.call(this)};g.w(B6,g.T);
B6.prototype.G=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.C(a.toggledServiceEndpoint):this.C(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;C6(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.Ib)this.j.Rb();else{var b=Lob(this);b&&this.C(b.serviceEndpoint||b.command);b=(null==(a=g.S(null==b?void 0:b.command,g.kG))?void 0:a.commands)||[];a:{a=g.u(b);for(var c=a.next();!c.done;c=a.next()){var d=b=void 0;if(c=null==(b=g.S(c.value,
g.Xeb))?void 0:null==(d=b.popup)?void 0:d.menuPopupRenderer){a=c;break a}}a=void 0}this.j||(this.j=new A6(this.J,this.buttonElement),this.j.Ga(this.element),g.L(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.C,this));b=this.j;b.menuPopupRenderer=a;Hob(b)}};
B6.prototype.C=function(a){var b=g.S(a,mpb),c=g.S(a,npb);if(a&&(b||c)){if(b){var d=b;var e="notification/add_upcoming_event_reminder"}else c&&(d=c,e="notification/remove_upcoming_event_reminder");if(e&&d&&d.params)for(Nob(this,e,d.params),a=g.u(d.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&g.S(b,opb)){this.B=g.S(b,opb).state;C6(this);break}}};g.w(Pob,g.T);g.k=Pob.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.Sa=function(a){var b,c,d=null==a?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:c.offlineSlate;if(d){this.B=a;b=d.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.D_():Qob(this,b);var e,f,h,l;if(c=null==a?void 0:null==(e=a.liveStreamability)?void 0:null==(f=e.liveStreamabilityRenderer)?void 0:null==(h=f.offlineSlate)?void 0:null==(l=h.liveStreamOfflineSlateRenderer)?void 0:l.thumbnail){e=0;f=null;h=c.thumbnails;for(l=0;l<h.length;l++)h[l].width>
e&&(e=h[l].width||0,f=h[l].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.j||(this.j=new B6(this.api),this.j.Ga(this.Ha("ytp-offline-slate-buttons")),g.L(this,this.j)),Job(this.j,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.j&&Job(this.j,null,null);this.B=a}else this.B=null;this.H_()};
g.k.H_=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.Vb(),d=this.getVideoData();b=d.isLivePlayback&&(g.ZL(c)||g.cH(c,2)||g.cH(c,64));var e=2===d.autonavState&&g.cH(c,2);c=c.isPlaying()&&!g.GT(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.B?this.Ib?(null==a?0:g.eH(a,2))&&!this.getVideoData().Tl&&(g.pu(this.element,"ytp-offline-slate-collapsed"),this.D.stop(),g.pu(this.C,"ytp-offline-slate-bar-fade"),this.G.start()):(this.show(),this.D.start(),this.api.ra("offlineslatestatechange"),
this.K&&this.api.eB()):this.Ib&&(this.hide(),this.api.ra("offlineslatestatechange"))};
g.k.D_=function(){var a,b,c,d,e=null==(a=this.B)?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:null==(d=c.offlineSlate)?void 0:d.liveStreamOfflineSlateRenderer;e&&(a=Math.floor(g.eb()/1E3),b=e.canShowCountdown&&Number(e.scheduledStartTime),!b||b<=a?(Qob(this,e),this.countdownTimer.stop()):(Qob(this,e,g.lH(b-a)),g.gu(this.countdownTimer)))};
g.k.Ba=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.T.prototype.Ba.call(this)};D6.prototype.B=function(a){return this.trigger&&a.trigger?this.module===a.module&&this.trigger===a.trigger&&this.j===a.j:!1};
D6.prototype.isExpired=function(){return 6E4<(0,g.OD)()-this.C};
D6.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.j};g.w(Yob,g.zV);g.k=Yob.prototype;g.k.Ba=function(){H6(this);this.player.lf("heartbeat");g.zV.prototype.Ba.call(this)};
g.k.onCueRangeEnter=function(){this.S=!0;F6(this,2E3)};
g.k.uE=function(a){this.heartbeatParams=a;F6(this,2E3)};
g.k.f1=function(a){var b;8!==this.player.getPresentingPlayerType()&&"UNPLAYABLE"!==(null==(b=this.j)?void 0:b.status)&&(g.cH(a.state,2)||g.cH(a.state,64)?(H6(this),this.D&&(this.S=!0,F6(this,1E3))):(g.cH(a.state,1)||g.cH(a.state,8))&&F6(this,2E3))};
g.k.j1=function(){3!==this.player.getPresentingPlayerType()&&F6(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.wl=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.xI=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.zD("heartbeatActionPlayerTransitioned",a)};
g.k.xf=function(a){var b="LICENSE",c=apb(a);if(c)return c.reason||g.XV[b]||"";(a=a.match(bpb))&&(a=Number(a[1]))&&(b=g.PAa(a));return g.XV[b]||""};
g.k.LD=function(){return!!this.offlineSlate&&this.offlineSlate.Ib};
var bpb=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.yV("heartbeat",Yob);})(_yt_player);
